id: IEE9AE36E
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-30T18:53:01.638498'
last_modified: '2022-05-30T18:53:01.638510'
parser: null
source_metadata:
  title: Dorje Dechen Lingpa Series
  language: en
  description: The following texts are available in our series of texts by or about
    Dorje Dechen Lingpa (rdo rje bde chen gling pa, 1857–1928), the reincarnation
    of Yongdzin Jinpa Gyatso, who founded Domang Monastery, and Lhatsün Namkha Jigme.
  volume:
    f7704:
      title: 'Summoning the Spirit of Abundance: A Rain of Flowers'
      base_file: f7704.txt
      order: 1
      parent: null
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
